language: php

os:
  - linux
  - osx

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master

before_script: composer install --prefer-source
script: phpunit

# Build environment and configuration documentation: 
# http://docs.travis-ci.com/user/languages/php/
