markdown: redcarpet
#highlighter: pygments
pygments: true
pygments_options: ['lineanchors', 'linenos=table']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data","tables"] 
